.github/workflows/validate-rust-gnullvm-arm64.ymlhttps://github.com/actions/runner-images/actions/runs/36123393221/job/108033891899#step:2:1images/windows/scripts/build/Install-Rust.ps1images/windows/scripts/tests/Rust.Tests.ps1name: Create GitHub release

on:.github/workflows/validate-rust-gnullvm-arm64.yml
  repository_dispatch:
    types: [create-github-release]


jobs:
  Create_GitHub_release:
    runs-on: ubuntu-latest

    steps:
    - name: Create release for ${{ github.event.client_payload.ReleaseBranchName }}
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b #v1.20.0
      with:
        tag: ${{ github.event.client_payload.ReleaseBranchName }}
        name: ${{ github.event.client_payload.ReleaseTitle }}
        body: ${{ github.event.client_payload.ReleaseBody }}
        prerelease: ${{ github.event.client_payload.Prerelease }}
        commit: ${{ github.event.client_payload.Commitish }}
        allowUpdates: true
